apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ac-app
  namespace: default
spec:
  interval: 15m
  path: "./fluxcd/repositories/ac-app/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: ac-app
